
drop VIEW  USER_ROLE_VW;
drop VIEW  USER_EMAIL_VW;
drop VIEW  USER_PHONE_VW;
DROP VIEW USER_IDENTITY_VW;
DROP VIEW USER_PSWD_EXPIRED_YESTERDAY_VW;

drop TABLE  SYNCH_CONFIG_DATA_MAPPING;
drop TABLE  SYNCH_CONFIG;
drop TABLE   RECONCILIATION_SITUATION;
drop TABLE  RECONCILIATION_CONFIG;
drop TABLE  ATTRIBUTE_MAP;
drop TABLE  REQUEST_USER;
drop TABLE  REQUEST_ATTRIBUTE;
drop TABLE  REQUEST_ATTACHMENT;
drop TABLE  MNG_SYS_LIST;
drop TABLE  REQ_APPROVER;
drop TABLE  PROV_REQUEST;
drop TABLE  MNG_SYS_GROUP;
drop TABLE  APPROVER_ASSOC;
drop TABLE  MANAGED_SYS_ATTRIBUTE;
drop TABLE  MNG_SYS_OBJECT_MATCH;
drop TABLE  MANAGED_SYS;
drop TABLE  PROVISION_CONNECTOR;
drop TABLE  RESOURCE_POLICY;
drop TABLE  ROLE_ENTITLEMENT;
drop TABLE  ENTITLEMENT;
drop TABLE  POLICY_OBJECT_ASSOC;
drop TABLE  POLICY_ATTRIBUTE;
drop TABLE  POLICY_DEF_PARAM;
drop TABLE  POLICY;
drop TABLE  POLICY_DEF;
drop TABLE  USER_IDENTITY_ANS;
drop TABLE  IDENTITY_QUESTION;
drop TABLE  IDENTITY_QUEST_GRP;
DROP TABLE  USER_PRIVILEGE;
DROP TABLE  RESOURCE_PRIVILEGE;
DROP TABLE  PRIVILEGE_DEF;
go

