package org.openiam.idm.srvc.user.dto;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;
import org.openiam.idm.srvc.user.domain.SupervisorEntity;

/**
 * Supervisor generated by hbm2java
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "supervisor", propOrder = {
        "comments",
        "employee",
        "endDate",
        "isPrimarySuper",
        "orgStructureId",
        "startDate",
        "status",
        "supervisor",
        "supervisorType"
})

public class Supervisor implements java.io.Serializable {

    protected String orgStructureId;

    protected String comments;

    protected User employee;

    protected Date endDate;

    protected Integer isPrimarySuper = new Integer(0);

    @XmlSchemaType(name = "dateTime")
    protected Date startDate;

    protected String status;

    protected User supervisor;

    protected String supervisorType;


    public Supervisor() {
    }

    public Supervisor(SupervisorEntity supervisorEntity) {
        this.orgStructureId = supervisorEntity.getOrgStructureId();
        this.comments = supervisorEntity.getComments();
        this.employee = new User(supervisorEntity.getEmployee());
        this.endDate = supervisorEntity.getEndDate();
        this.isPrimarySuper = supervisorEntity.getPrimarySuper();
        this.startDate = supervisorEntity.getStartDate();
        this.status = supervisorEntity.getStatus();
        this.supervisor = new User(supervisorEntity.getSupervisor());
        this.supervisorType = supervisorEntity.getSupervisorType();
    }

    public Supervisor(String orgStructureId, User usersBySupervisorId, User employee) {
        this.orgStructureId = orgStructureId;
        this.supervisor = usersBySupervisorId;
        this.employee = employee;
    }

    public Supervisor(String orgStructureId,
                      User usersBySupervisorId,
                      User employee,
                      String supervisorType,
                      Integer isPrimarySuper,
                      Date startDate,
                      Date endDate,
                      String status,
                      String comments) {
        this.orgStructureId = orgStructureId;
        this.supervisor = usersBySupervisorId;
        this.employee = employee;
        this.supervisorType = supervisorType;
        this.isPrimarySuper = isPrimarySuper;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
        this.comments = comments;
    }

    public String getOrgStructureId() {
        return this.orgStructureId;
    }

    public void setOrgStructureId(String orgStructureId) {
        this.orgStructureId = orgStructureId;
    }

    public User getEmployee() {
        return employee;
    }

    public void setEmployee(User employee) {
        this.employee = employee;
    }

    public User getSupervisor() {
        return supervisor;
    }

    public void setSupervisor(User supervisor) {
        this.supervisor = supervisor;
    }

    public String getSupervisorType() {
        return this.supervisorType;
    }

    public void setSupervisorType(String supervisorType) {
        this.supervisorType = supervisorType;
    }

    public Integer getIsPrimarySuper() {
        return this.isPrimarySuper;
    }

    public void setIsPrimarySuper(Integer isPrimarySuper) {
        this.isPrimarySuper = isPrimarySuper;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "Supervisor{" +
                "comments='" + comments + '\'' +
                ", employee=" + employee +
                ", endDate=" + endDate +
                ", isPrimarySuper=" + isPrimarySuper +
                ", orgStructureId='" + orgStructureId + '\'' +
                ", startDate=" + startDate +
                ", status='" + status + '\'' +
                ", supervisor=" + supervisor +
                ", supervisorType='" + supervisorType + '\'' +
                '}';
    }
}


