package org.openiam.idm.srvc.user.dto;

// Generated Jun 12, 2007 10:46:13 PM by Hibernate Tools 3.2.0.beta8

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Date;
import org.openiam.idm.srvc.user.domain.UserNoteEntity;


/**
 * UserNote generated by hbm2java
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userNote", propOrder = {
        "createDate",
        "createdBy",
        "description",
        "noteType",
        "userId",
        "userNoteId"
})

public class UserNote implements java.io.Serializable {

    // Fields
    protected String userNoteId;

    @XmlSchemaType(name = "dateTime")
    protected Date createDate;

    protected String createdBy;

    protected String description;

    protected String noteType;

    protected String userId;
    // Constructors

    /**
     * default constructor
     */
    public UserNote() {
    }

    public UserNote(UserNoteEntity userNoteEntity) {
        this.userNoteId = userNoteEntity.getUserNoteId();
        this.createDate = userNoteEntity.getCreateDate();
        this.createdBy = userNoteEntity.getCreatedBy();
        this.description = userNoteEntity.getDescription();
        this.noteType = userNoteEntity.getNoteType();
        this.userId = userNoteEntity.getUser() != null ? userNoteEntity.getUser().getUserId() : "";
    }

    /**
     *
     * @return userNoteId
     */
    public String getUserNoteId() {
        return userNoteId;
    }

    public void setUserNoteId(String userNoteId) {
        this.userNoteId = userNoteId;
    }

    public String getUserId() {
        return userId;
    }

    public String getNoteType() {
        return this.noteType;
    }

    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
}
