CREATE TABLE MAIL_TEMPLATE(
	TMPL_ID VARCHAR(32) NOT NULL,
	TMPL_NAME VARCHAR(64) NOT NULL UNIQUE,
    TMPL_SUBJECT VARCHAR(64) NOT NULL,
    BODY_TYPE VARCHAR(16) NOT NULL,
    ATTACHMENT_FILE_PATH VARCHAR(64),
    BODY TEXT,
    PRIMARY KEY (TMPL_ID)
)Engine=InnoDB;

CREATE TABLE NOTIFICATION(
	MSG_ID VARCHAR(32) NOT NULL,
	MSG_NAME VARCHAR(64) NOT NULL UNIQUE,
    PROVIDER_SCRIPT VARCHAR(64),
    TMPL_ID VARCHAR(32),
    START_DATE  DATE NULL,
    END_DATE  DATE NULL,
    MSG_TYPE VARCHAR(32),
    PRIMARY KEY (MSG_ID),
    CONSTRAINT FK_NOTIFICATION_MESSAGE_MAIL_TEMPLATE
       FOREIGN KEY (TMPL_ID)
       REFERENCES MAIL_TEMPLATE(TMPL_ID)
)Engine=InnoDB;

INSERT INTO MENU (menu_id, menu_group, menu_name,menu_desc,url,LANGUAGE_CD, DISPLAY_ORDER) values('MAIL_TEMPLATES','ADMIN','Mail Templates','Mail Templates','mailTmplList.cnt', 'en',7);
INSERT INTO PERMISSIONS(MENU_ID,ROLE_ID,SERVICE_ID) VALUES('MAIL_TEMPLATES','SUPER_SEC_ADMIN','IDM');

INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('402881823ba67a37013ba68159740001','BulkUsersMessage','BulkNotificationByUserIds.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8e9af410001','NEW_USER_EMAIL','NewUserCreateNotification.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ea53030002','NEW_USER_EMAIL_SUPERVISOR','NewUserCreateToSupervisorNotification.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ea91d10003','REQUEST_APPROVED','RequestApproveNotification.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8eb000c0004','REQUEST_REJECTED','RequestRejectNotification.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ebe3380005','NEW_PENDING_REQUEST','RequestNotification.groovy','SYSTEM');
INSERT INTO NOTIFICATION(MSG_ID,MSG_NAME,PROVIDER_SCRIPT,MSG_TYPE) VALUES('8a0081053ba8db9d013ba8ec3e580006','REQUEST_PASSWORD_RESET','RequestPasswordResetNotification.groovy','SYSTEM');

