ALTER TABLE MANAGED_SYS change HNDLR_1 SEARCH_HNDLR VARCHAR(100);
ALTER TABLE MANAGED_SYS change HNDLR_2 LOOKUP_HNDLR VARCHAR(100);
ALTER TABLE MANAGED_SYS change HNDLR_3 TEST_CONNECTION_HNDLR VARCHAR(100);
ALTER TABLE MANAGED_SYS change HNDLR_4 RECONCILE_RESOURCE_HNDLR VARCHAR(100);