use openiam;
CREATE TABLE REPORT_CRITERIA_PARAMETER (
    RCP_ID VARCHAR(32) NOT NULL,
    REPORT_INFO_ID VARCHAR(32) NOT NULL,
	  PARAM_NAME VARCHAR(64) NOT NULL,
    PARAM_VALUE VARCHAR(64),
    PRIMARY KEY (RCP_ID),
    CONSTRAINT FK_REPORT_CRITERIA_PARAMETER_REPORT_INFO
       FOREIGN KEY (REPORT_INFO_ID)
       REFERENCES REPORT_INFO(REPORT_INFO_ID),
    UNIQUE KEY UK_REPORT_INFO_ID_PARAM_NAME (REPORT_INFO_ID, PARAM_NAME)
) Engine=InnoDB;