use openiam;
DROP TABLE IF EXISTS REPORT_CRITERIA_PARAMETER;
CREATE TABLE REPORT_CRITERIA_PARAMETER (
    RCP_ID VARCHAR(32) NOT NULL,
    REPORT_INFO_ID VARCHAR(32) NOT NULL,
	PARAM_NAME VARCHAR(64) NOT NULL,
    PARAM_VALUE VARCHAR(64),
    RCPT_ID VARCHAR(64) NOT NULL,
    PRIMARY KEY (RCP_ID),
    CONSTRAINT FK_REPORT_CRITERIA_PARAMETER_REPORT_INFO
       FOREIGN KEY (REPORT_INFO_ID)
       REFERENCES REPORT_INFO(REPORT_INFO_ID),
    CONSTRAINT FK_REPORT_CRITERIA_PARAMETER_REPORT_PARAMETER_TYPE
       FOREIGN KEY (RCPT_ID)
       REFERENCES REPORT_PARAMETER_TYPE(RCPT_ID),
    UNIQUE KEY UK_REPORT_INFO_ID_PARAM_NAME (REPORT_INFO_ID, PARAM_NAME)
) Engine=InnoDB;

DROP TABLE IF EXISTS REPORT_PARAMETER_TYPE;
CREATE TABLE REPORT_PARAMETER_TYPE (
    RCPT_ID VARCHAR(32) NOT NULL,
    TYPE_NAME VARCHAR(64) NOT NULL UNIQUE,
    TYPE_DESCRIPTION VARCHAR(128),
    PRIMARY KEY (RCPT_ID)
) Engine=InnoDB;

INSERT INTO REPORT_PARAMETER_TYPE(RCPT_ID, TYPE_NAME,TYPE_DESCRIPTION) VALUES ('1', 'STRING','String');
INSERT INTO REPORT_PARAMETER_TYPE(RCPT_ID, TYPE_NAME,TYPE_DESCRIPTION) VALUES ('2', 'DATE','Date');


