use openiam;
DROP TABLE IF EXISTS WEB_RESOURCE_ATTRIBUTE;
create table WEB_RESOURCE_ATTRIBUTE(
	ATTRIBUTE_MAP_ID varchar(32) NOT NULL,
	RESOURCE_ID varchar(32) NOT NULL,
	TARGET_ATTRIBUTE_NAME varchar(100) NOT NULL,
	AM_ATTRIBUTE_NAME varchar(100) NULL,
	AM_POLICY_URL varchar(100) NULL,
	primary key(ATTRIBUTE_MAP_ID),
	UNIQUE (RESOURCE_ID, TARGET_ATTRIBUTE_NAME)
)Engine=InnoDB;
